language: python
dist: xenial
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"

cache: pip

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml libenchant-dev"
  - "pip install -r ./travis/requirements.txt"

script:
  - "py.test -v"

after_success:
  - 'coverage xml'
  - 'coveralls'
  - 'python-codacy-coverage -r coverage.xml'

env:
  - PYTHONPATH=.
  - PYTHONPATH=. PYTHONASYNCIODEBUG=1
